---
apiVersion: platform.confluent.io/v1beta1
kind: Connect
metadata:
  name: connect
  # annotations:
  #   platform.confluent.io/disable-internal-rolebindings-creation: "true"
spec:
  replicas: 1
  image:
    application: confluentinc/cp-server-connect:7.4.0
    init: confluentinc/confluent-init-container:2.6.0
  tls:
    directoryPathInContainer: /vault/secrets
  # license:
  #   directoryPathInContainer: /vault/secrets
  authorization:
    type: rbac
  externalAccess:
    type: loadBalancer
    loadBalancer:
      domain: mydomain.example
      prefix: connect
  podTemplate:
    resources:
      requests:
        memory: "50Mi"
        cpu: "250m"
      limits:
        memory: "500Mi"
        cpu: "500m"
    serviceAccountName: confluent-sa
    annotations:
      vault.hashicorp.com/agent-inject: "true"
      vault.hashicorp.com/agent-inject-status: update
      vault.hashicorp.com/preserve-secret-case: "true"
      vault.hashicorp.com/agent-inject-secret-jksPassword.txt: secret/jksPassword.txt
      vault.hashicorp.com/agent-inject-template-jksPassword.txt: |
        {{- with secret "secret/jksPassword.txt" -}}
        {{ .Data.data.password }}
        {{- end }}
      vault.hashicorp.com/agent-inject-secret-keystore.jks: secret/connect-keystore.jks
      vault.hashicorp.com/agent-inject-template-keystore.jks: |
        {{- with secret "secret/connect-keystore.jks" -}}
        {{ .Data.data.keystore | base64Decode }}
        {{- end }}
      vault.hashicorp.com/agent-inject-secret-truststore.jks: secret/truststore.jks
      vault.hashicorp.com/agent-inject-template-truststore.jks: |
        {{- with secret "secret/truststore.jks" -}}
        {{ .Data.data.truststore | base64Decode }}
        {{- end }}
      vault.hashicorp.com/secret-volume-path-connect-bearer: /vault/secrets/connect
      vault.hashicorp.com/agent-inject-secret-connect-bearer: secret/connect/bearer.txt
      vault.hashicorp.com/agent-inject-file-connect-bearer: bearer.txt # this are mandatory name
      vault.hashicorp.com/agent-inject-template-connect-bearer: |
        {{- with secret "secret/connect/bearer.txt" -}}
        {{ .Data.data.bearer | base64Decode }}
        {{- end }}
      vault.hashicorp.com/agent-inject-secret-kafka-client-sasl-plain: secret/kafka-client/plain-jaas.conf
      vault.hashicorp.com/secret-volume-path-kafka-client-sasl-plain: /vault/secrets/jaas
      vault.hashicorp.com/agent-inject-file-kafka-client-sasl-plain: plain-jaas.conf # this are mandatory names
      vault.hashicorp.com/agent-inject-template-kafka-client-sasl-plain: |
        {{- with secret "secret/kafka-client/plain-jaas.conf" -}}
        {{ .Data.data.plainjaas | base64Decode }}
        {{- end }}
      vault.hashicorp.com/agent-inject-secret-license: secret/license.txt
      vault.hashicorp.com/agent-inject-file-license: license.txt # this are mandatory names
      vault.hashicorp.com/agent-inject-template-license: |
        {{- with secret "secret/license.txt" -}}
        {{ .Data.data.license | base64Decode }}
        {{- end }}
      vault.hashicorp.com/agent-inject-secret-mds-publickey: secret/mds-publickey.txt
      vault.hashicorp.com/agent-inject-file-mds-publickey: mdsPublicKey.pem # must be with this name
      vault.hashicorp.com/agent-inject-template-mds-publickey: |
        {{- with secret "secret/mds-publickey.txt" -}}
        {{ .Data.data.mdspublickey | base64Decode }}
        {{- end }}
      vault.hashicorp.com/role: confluent-operator
  dependencies:
    kafka:
      bootstrapEndpoint: kafka.confluent.svc.cluster.local:9071
      authentication:
        type: mtls
      tls:
        enabled: true
    mds:
      endpoint: https://kafka.confluent.svc.cluster.local:8090
      tokenKeyPair:
        directoryPathInContainer: /vault/secrets
      authentication:
        type: bearer
        bearer:
          directoryPathInContainer: /vault/secrets/connect
      tls:
        enabled: true
    schemaRegistry:
      url: https://schemaregistry.confluent.svc.cluster.local:8081
      tls:
        enabled: true


---
apiVersion: platform.confluent.io/v1beta1
kind: SchemaRegistry
metadata:
  name: schemaregistry
  # annotations:
    # platform.confluent.io/disable-internal-rolebindings-creation: "true"
spec:
  replicas: 1
  image:
    application: confluentinc/cp-schema-registry:7.4.0
    init: confluentinc/confluent-init-container:2.6.0
  tls:
    directoryPathInContainer: /vault/secrets
  license:
    directoryPathInContainer: /vault/secrets
  authorization:
    type: rbac
  externalAccess:
    type: loadBalancer
    loadBalancer:
      domain: mydomain.example
      prefix: sr
  configOverrides:
    server:
    - confluent.license.topic=_confluent-command
  podTemplate:
    resources:
      requests:
        memory: "50Mi"
        cpu: "250m"
      limits:
        memory: "500Mi"
        cpu: "500m"
    serviceAccountName: confluent-sa
    annotations:
      vault.hashicorp.com/agent-inject: "true"
      vault.hashicorp.com/agent-inject-status: update
      vault.hashicorp.com/preserve-secret-case: "true"
      vault.hashicorp.com/agent-inject-secret-jksPassword.txt: secret/jksPassword.txt
      vault.hashicorp.com/agent-inject-template-jksPassword.txt: |
        {{- with secret "secret/jksPassword.txt" -}}
        {{ .Data.data.password }}
        {{- end }}
      vault.hashicorp.com/secret-volume-path-keystore.jks: /vault/secrets
      vault.hashicorp.com/agent-inject-file-keystore.jks: keystore.jks
      vault.hashicorp.com/agent-inject-secret-keystore.jks: secret/schemaregistry-keystore.jks
      vault.hashicorp.com/agent-inject-template-keystore.jks: |-
        {{- with secret "secret/schemaregistry-keystore.jks" -}}
        {{ .Data.data.keystore | base64Decode }}
        {{- end }}
      vault.hashicorp.com/agent-inject-secret-truststore.jks: secret/truststore.jks
      vault.hashicorp.com/agent-inject-template-truststore.jks: |
        {{- with secret "secret/truststore.jks" -}}
        {{ .Data.data.truststore | base64Decode }}
        {{- end }}
      vault.hashicorp.com/secret-volume-path-sr-bearer: /vault/secrets/schemaregistry
      vault.hashicorp.com/agent-inject-secret-sr-bearer: secret/schemaregistry/bearer.txt
      vault.hashicorp.com/agent-inject-file-sr-bearer: bearer.txt # this are mandatory name
      vault.hashicorp.com/agent-inject-template-sr-bearer: |
        {{- with secret "secret/schemaregistry/bearer.txt" -}}
        {{ .Data.data.bearer | base64Decode }}
        {{- end }}
      vault.hashicorp.com/agent-inject-secret-kafka-client-sasl-plain: secret/kafka-client/plain-jaas.conf
      vault.hashicorp.com/secret-volume-path-kafka-client-sasl-plain: /vault/secrets/jaas
      vault.hashicorp.com/agent-inject-file-kafka-client-sasl-plain: plain-jaas.conf # this are mandatory names
      vault.hashicorp.com/agent-inject-template-kafka-client-sasl-plain: |
        {{- with secret "secret/kafka-client/plain-jaas.conf" -}}
        {{ .Data.data.plainjaas | base64Decode }}
        {{- end }}
      vault.hashicorp.com/agent-inject-secret-license: secret/license.txt
      vault.hashicorp.com/agent-inject-file-license: license.txt # this are mandatory names
      vault.hashicorp.com/agent-inject-template-license: |
        {{- with secret "secret/license.txt" -}}
        {{ .Data.data.license | base64Decode }}
        {{- end }}
      vault.hashicorp.com/agent-inject-secret-mds-publickey: secret/mds-publickey.txt
      vault.hashicorp.com/agent-inject-file-mds-publickey: mdsPublicKey.pem # must be with this name
      vault.hashicorp.com/agent-inject-template-mds-publickey: |
        {{- with secret "secret/mds-publickey.txt" -}}
        {{ .Data.data.mdspublickey | base64Decode }}
        {{- end }}
      vault.hashicorp.com/role: confluent-operator
  dependencies:
    kafka:
      bootstrapEndpoint: kafka.confluent.svc.cluster.local:9071
      authentication:
        type: mtls
      tls:
        enabled: true
    mds:
      endpoint: https://kafka.confluent.svc.cluster.local:8090
      tokenKeyPair:
        directoryPathInContainer: /vault/secrets
      authentication:
        type: bearer
        bearer:
          directoryPathInContainer: /vault/secrets/schemaregistry
      tls:
        enabled: true

---
apiVersion: platform.confluent.io/v1beta1
kind: KsqlDB
metadata:
  name: ksqldb
  namespace: confluent
  # annotations:
  #   platform.confluent.io/disable-internal-rolebindings-creation: "true"
spec:
  replicas: 1
  image:
    application: confluentinc/cp-ksqldb-server:7.4.0
    init: confluentinc/confluent-init-container:2.6.0
  dataVolumeCapacity: 10Gi
  authorization:
    type: rbac
  externalAccess:
    type: loadBalancer
    loadBalancer:
      domain: mydomain.example
      prefix: ksqldb
  tls:
    directoryPathInContainer: /vault/secrets
  license:
    directoryPathInContainer: /vault/secrets
  # configOverrides:
  #   server:
  #     - ksql.schema.registry.url=https://schemaregistry.confluent.svc.cluster.local:8081
  podTemplate:
    resources:
      requests:
        memory: "50Mi"
        cpu: "250m"
      limits:
        memory: "500Mi"
        cpu: "500m"
    serviceAccountName: confluent-sa
    annotations:
      vault.hashicorp.com/agent-inject: "true"
      vault.hashicorp.com/agent-inject-status: update
      vault.hashicorp.com/preserve-secret-case: "true"
      vault.hashicorp.com/agent-inject-secret-jksPassword.txt: secret/jksPassword.txt
      vault.hashicorp.com/agent-inject-template-jksPassword.txt: |
        {{- with secret "secret/jksPassword.txt" -}}
        {{ .Data.data.password }}
        {{- end }}
      vault.hashicorp.com/secret-volume-path-keystore.jks: /vault/secrets
      vault.hashicorp.com/agent-inject-file-keystore.jks: keystore.jks
      vault.hashicorp.com/agent-inject-secret-keystore.jks: secret/ksqldb-keystore.jks
      vault.hashicorp.com/agent-inject-template-keystore.jks: |-
        {{- with secret "secret/ksqldb-keystore.jks" -}}
        {{ .Data.data.keystore | base64Decode }}
        {{- end }}
      vault.hashicorp.com/agent-inject-secret-truststore.jks: secret/truststore.jks
      vault.hashicorp.com/agent-inject-template-truststore.jks: |
        {{- with secret "secret/truststore.jks" -}}
        {{ .Data.data.truststore | base64Decode }}
        {{- end }}
      vault.hashicorp.com/secret-volume-path-ksqldb-bearer: /vault/secrets/ksqldb
      vault.hashicorp.com/agent-inject-secret-ksqldb-bearer: secret/ksqldb/bearer.txt
      vault.hashicorp.com/agent-inject-file-ksqldb-bearer: bearer.txt # this are mandatory name
      vault.hashicorp.com/agent-inject-template-ksqldb-bearer: |
        {{- with secret "secret/ksqldb/bearer.txt" -}}
        {{ .Data.data.bearer | base64Decode }}
        {{- end }}
      vault.hashicorp.com/agent-inject-secret-kafka-client-sasl-plain: secret/kafka-client/plain-jaas.conf
      vault.hashicorp.com/secret-volume-path-kafka-client-sasl-plain: /vault/secrets/jaas
      vault.hashicorp.com/agent-inject-file-kafka-client-sasl-plain: plain-jaas.conf # this are mandatory names
      vault.hashicorp.com/agent-inject-template-kafka-client-sasl-plain: |
        {{- with secret "secret/kafka-client/plain-jaas.conf" -}}
        {{ .Data.data.plainjaas | base64Decode }}
        {{- end }}
      vault.hashicorp.com/agent-inject-secret-license: secret/license.txt
      vault.hashicorp.com/agent-inject-file-license: license.txt # this are mandatory names
      vault.hashicorp.com/agent-inject-template-license: |
        {{- with secret "secret/license.txt" -}}
        {{ .Data.data.license | base64Decode }}
        {{- end }}
      vault.hashicorp.com/agent-inject-secret-mds-publickey: secret/mds-publickey.txt
      vault.hashicorp.com/agent-inject-file-mds-publickey: mdsPublicKey.pem # must be with this name
      vault.hashicorp.com/agent-inject-template-mds-publickey: |
        {{- with secret "secret/mds-publickey.txt" -}}
        {{ .Data.data.mdspublickey | base64Decode }}
        {{- end }}
      vault.hashicorp.com/role: confluent-operator
  dependencies:
    kafka:
      bootstrapEndpoint: kafka.confluent.svc.cluster.local:9071
      authentication:
        type: mtls
      tls:
        enabled: true
    schemaRegistry:
      url: https://schemaregistry.confluent.svc.cluster.local:8081
      tls:
        enabled: true
    mds:
      endpoint: https://kafka.confluent.svc.cluster.local:8090
      tokenKeyPair:
        directoryPathInContainer: /vault/secrets
      authentication:
        type: bearer
        bearer:
          directoryPathInContainer: /vault/secrets/ksqldb
      tls:
        enabled: true

---
apiVersion: platform.confluent.io/v1beta1
kind: ControlCenter
metadata:
  name: controlcenter
  # annotations:
  #   platform.confluent.io/disable-internal-rolebindings-creation: "true"
spec:
  replicas: 1
  image:
    application: confluentinc/cp-enterprise-control-center:7.4.0
    init: confluentinc/confluent-init-container:2.6.0
  dataVolumeCapacity: 10Gi
  authorization:
    type: rbac
  externalAccess:
    type: loadBalancer
    loadBalancer:
      domain: mydomain.example
      prefix: controlcenter
  configOverrides:
    log4j:
    - log4j.rootLogger=DEBUG, stdout
    server:
    # reduced infrastructure mode
    - confluent.controlcenter.mode.enable=management
  tls:
    directoryPathInContainer: /vault/secrets
  license:
    directoryPathInContainer: /vault/secrets
  podTemplate:
    resources:
      requests:
        memory: "50Mi"
        cpu: "250m"
      limits:
        memory: "2Gi"
        cpu: "500m"
    probe:
      liveness:
        periodSeconds: 10
        failureThreshold: 5
        timeoutSeconds: 500
    serviceAccountName: confluent-sa
    annotations:
      vault.hashicorp.com/agent-inject: "true"
      vault.hashicorp.com/agent-inject-status: update
      vault.hashicorp.com/preserve-secret-case: "true"
      vault.hashicorp.com/agent-inject-secret-jksPassword.txt: secret/jksPassword.txt
      vault.hashicorp.com/agent-inject-template-jksPassword.txt: |
        {{- with secret "secret/jksPassword.txt" -}}
        {{ .Data.data.password }}
        {{- end }}
      vault.hashicorp.com/secret-volume-path-keystore.jks: /vault/secrets
      vault.hashicorp.com/agent-inject-file-keystore.jks: keystore.jks
      vault.hashicorp.com/agent-inject-secret-keystore.jks: secret/controlcenter-keystore.jks
      vault.hashicorp.com/agent-inject-template-keystore.jks: |-
        {{- with secret "secret/controlcenter-keystore.jks" -}}
        {{ .Data.data.keystore | base64Decode }}
        {{- end }}
      vault.hashicorp.com/agent-inject-secret-truststore.jks: secret/truststore.jks
      vault.hashicorp.com/agent-inject-template-truststore.jks: |
        {{- with secret "secret/truststore.jks" -}}
        {{ .Data.data.truststore | base64Decode }}
        {{- end }}
      vault.hashicorp.com/secret-volume-path-controlcenter-bearer: /vault/secrets/c3
      vault.hashicorp.com/agent-inject-secret-controlcenter-bearer: secret/controlcenter/bearer.txt
      vault.hashicorp.com/agent-inject-file-controlcenter-bearer: bearer.txt # this are mandatory name
      vault.hashicorp.com/agent-inject-template-controlcenter-bearer: |
        {{- with secret "secret/controlcenter/bearer.txt" -}}
        {{ .Data.data.bearer | base64Decode }}
        {{- end }}
      vault.hashicorp.com/agent-inject-secret-kafka-client-sasl-plain: secret/kafka-client/plain-jaas.conf
      vault.hashicorp.com/secret-volume-path-kafka-client-sasl-plain: /vault/secrets/jaas
      vault.hashicorp.com/agent-inject-file-kafka-client-sasl-plain: plain-jaas.conf # this are mandatory names
      vault.hashicorp.com/agent-inject-template-kafka-client-sasl-plain: |
        {{- with secret "secret/kafka-client/plain-jaas.conf" -}}
        {{ .Data.data.plainjaas | base64Decode }}
        {{- end }}
      vault.hashicorp.com/agent-inject-secret-license: secret/license.txt
      vault.hashicorp.com/agent-inject-file-license: license.txt
      vault.hashicorp.com/agent-inject-template-license: |
        {{- with secret "secret/license.txt" -}}
        {{ .Data.data.license | base64Decode }}
        {{- end }}
      vault.hashicorp.com/agent-inject-secret-mds-publickey: secret/mds-publickey.txt
      vault.hashicorp.com/agent-inject-file-mds-publickey: mdsPublicKey.pem # must be with this name
      vault.hashicorp.com/agent-inject-template-mds-publickey: |
        {{- with secret "secret/mds-publickey.txt" -}}
        {{ .Data.data.mdspublickey | base64Decode }}
        {{- end }}
      vault.hashicorp.com/role: confluent-operator
  dependencies:
    kafka:
      bootstrapEndpoint: kafka:9071
      authentication:
        type: mtls
      tls:
        enabled: true
    schemaRegistry:
      url: https://schemaregistry:8081
      tls:
        enabled: true
    ksqldb:
    - name: ksqldb
      url: https://ksqldb:8088
      tls:
        enabled: true
    connect:
    - name: connect
      url:  https://connect:8083
      tls:
        enabled: true
    mds:
      endpoint: https://kafka:8090
      tokenKeyPair:
        directoryPathInContainer: /vault/secrets
      authentication:
        type: bearer
        bearer:
          directoryPathInContainer: /vault/secrets/c3
      tls:
        enabled: true


---
apiVersion: platform.confluent.io/v1beta1
kind: KafkaRestClass
metadata:
  name: default
spec:
  kafkaRest:
    authentication:
      type: bearer
      bearer:
        secretRef: rest-credential

---
apiVersion: platform.confluent.io/v1beta1
kind: KafkaRestProxy
metadata:
  name: kafkarestproxy
  namespace: confluent
spec:
  replicas: 1
  image:
    application: confluentinc/cp-kafka-rest:7.4.0
    init: confluentinc/confluent-init-container:2.6.0
  tls:
    directoryPathInContainer: /vault/secrets
  externalAccess:
    type: loadBalancer
    loadBalancer:
      domain: mydomain.example
      prefix: kafkaresproxy
  dependencies:
    kafka:
      bootstrapEndpoint: kafka.confluent.svc.cluster.local:9071
      authentication:
        type: mtls
      tls:
        enabled: true
  podTemplate:
    resources:
      requests:
        memory: "50Mi"
        cpu: "250m"
      limits:
        memory: "500Mi"
        cpu: "500m"
    serviceAccountName: confluent-sa
    annotations:
      vault.hashicorp.com/agent-inject: "true"
      vault.hashicorp.com/agent-inject-status: update
      vault.hashicorp.com/preserve-secret-case: "true"
      vault.hashicorp.com/agent-inject-secret-jksPassword.txt: secret/jksPassword.txt
      vault.hashicorp.com/agent-inject-template-jksPassword.txt: |
        {{- with secret "secret/jksPassword.txt" -}}
        {{ .Data.data.password }}
        {{- end }}
      vault.hashicorp.com/secret-volume-path-keystore.jks: /vault/secrets
      vault.hashicorp.com/agent-inject-file-keystore.jks: keystore.jks
      vault.hashicorp.com/agent-inject-secret-keystore.jks: secret/kafkarestproxy-keystore.jks
      vault.hashicorp.com/agent-inject-template-keystore.jks: |-
        {{- with secret "secret/kafkarestproxy-keystore.jks" -}}
        {{ .Data.data.keystore | base64Decode }}
        {{- end }}
      vault.hashicorp.com/agent-inject-secret-truststore.jks: secret/truststore.jks
      vault.hashicorp.com/agent-inject-template-truststore.jks: |
        {{- with secret "secret/truststore.jks" -}}
        {{ .Data.data.truststore | base64Decode }}
        {{- end }}
      vault.hashicorp.com/agent-inject-secret-license: secret/license.txt
      vault.hashicorp.com/agent-inject-file-license: license.txt
      vault.hashicorp.com/agent-inject-template-license: |
        {{- with secret "secret/license.txt" -}}
        {{ .Data.data.license | base64Decode }}
        {{- end }}
      vault.hashicorp.com/role: confluent-operator
